### ISSUE TITLE
This Job has 'PlotterUsed' not set in LogStat. Was created using an old version.

### ISSUE THREAD

**Issue by Yamanipanuchi** [tydeno/Ploto#109]
Keep getting ..

`Get-PlotoJobs @ 7/12/2021 3:54:20 PM : This Job has 'PlotterUsed' not set in LogStat. Was created using an old version.
Get-PlotoJobs @ 7/12/2021 3:54:20 PM : Setting PlotterUsed in logstat to 'Chia'`

When I try to run Ploto. I did have an older version and just upgraded it.

**Comment by Yamanipanuchi** [comment]
`PS C:\Users\User\Desktop\Ploto> .\Install-Ploto.ps1
InstallPloto @ 7/12/2021 4:00:25 PM : Hello there! My Name is Ploto. This script guides you trough the setup of myself.
InstallPloto @07/12/2021 16:00:25: Path I got launched from: C:\Users\User\Desktop\Ploto
InstallPloto @ 7/12/2021 4:00:25 PM : Installing Version: 1.1.2 of Ploto on this machine.
InstallPloto @ 7/12/2021 4:00:25 PM : Lets check if a version of Ploto is installed in: C:\Program Files\WindowsPowerShell\Modules
InstallPloto @ 7/12/2021 4:00:25 PM : There is a version of Ploto installed in: C:\Program Files\WindowsPowerShell\Modules
InstallPloto @ 7/12/2021 4:00:25 PM : Current version installed: 1.1.2
InstallPloto @ 7/12/2021 4:00:25 PM : Version in downloaded Source is newer or the same as installed Version.
InstallPloto: Do you want to update your existing version?: y
InstallPloto @ 7/12/2021 4:00:41 PM : Starting update of Module...
InstallPloto @ 7/12/2021 4:00:41 PM : Deleting old version in: C:\Program Files\WindowsPowerShell\Modules\Ploto
InstallPloto @ 7/12/2021 4:00:41 PM : Successfully removed previous version of Ploto in: C:\Program Files\WindowsPowerShell\Modules\Ploto
InstallPloto @ 7/12/2021 4:00:41 PM : Copied Module successfully to: C:\Program Files\WindowsPowerShell\Modules\
InstallPloto @ 7/12/2021 4:00:41 PM : Lets check the current set Execution Policy...
InstallPloto @ 7/12/2021 4:00:41 PM : Execution Policy is set to:  Bypass
InstallPloto @ 7/12/2021 4:00:41 PM : Wooho! I've managed to imort the Ploto Module!
InstallPloto @ 7/12/2021 4:00:41 PM : Okay, next step is getting the config and setting it together with you...
InstallPloto @ 7/12/2021 4:00:41 PM : Checking if we have new properties in config from new version...
InstallPloto @ 7/12/2021 4:00:41 PM : No new properties were introduced in config
InstallPloto: Do you want to set the config? If not, we skip that, because you alreay have one in place (eg. Yes or y): n
InstallPloto @ 7/12/2021 4:00:49 PM : We skipped setting the config. Only updated Ploto Module.
InstallPloto @ 7/12/2021 4:00:49 PM : Ploto was installed correctly on this System.
InstallPloto @ 7/12/2021 4:00:49 PM : To launch it, start a PowerShell Session and run 'Start-PlotoSpawns'
PS C:\Users\User\Desktop\Ploto>`

**Comment by KillaDreams** [comment]
You literally need to copy the config from the new version over the old version in .chia/config folder and set up everything again copy paste whatever is easier for you to do 

If you notice the config file has changed from the old version so it's missing variables needed to launch the new ploto.psm1

**Comment by Yamanipanuchi** [comment]
Ya, I thought it was just picking an old config file up. But I have the new config file in the .chia/mainnet/config folder. I've checked several times.

**Comment by Yamanipanuchi** [comment]
It is definitely getting a config file from someplace also. I just deleted the one from chia/mainnet/config and it still give me that error.

Going to see about deleting all the config files except the one in that folder. See what happens.

**Comment by Yamanipanuchi** [comment]
Went through the config again via the script and got the following....

`Enter 'Yes' or 'y' to continue. Every other inpout aborts.: y
Get-PlotoJobs @ 7/13/2021 7:57:26 AM : This Job has 'PlotterUsed' not set in LogStat. Was created using an old version.
Get-PlotoJobs @ 7/13/2021 7:57:26 AM : Setting PlotterUsed in logstat to 'Chia'
InstallPloto @ 7/13/2021 7:57:26 AM : Could not copy config to:
You cannot call a method on a null-valued expression.
PS C:\Users\User\Desktop\Ploto>`

**Comment by Yamanipanuchi** [comment]
It is reading the config because this following info changes eachtime I run the script...

PS C:\Windows\system32> Start-PlotoSpawns
PlotoManager @ 7/13/2021 8:14:14 AM : Ploto Manager started.
PlotoManager @ 7/13/2021 8:14:14 AM : Checking paths...
PlotoManager @ 7/13/2021 8:14:14 AM : plotter folder available.
PlotoManager @ 7/13/2021 8:14:14 AM : Loading config from  C:\Users\User\.chia\mainnet\config\PlotoSpawnerConfig.json...
PlotoManager @ 7/13/2021 8:14:14 AM : Loaded config successfully.
--------------------------------------------------------------------------------------------------
PlotoManager @ 7/13/2021 8:14:14 AM : BaseConfig
PlotoManager @ 7/13/2021 8:14:14 AM : Alerts Enabled: true
PlotoManager @ 7/13/2021 8:14:14 AM : DiscordWebhookURL: https://discord.com/api/webhooks/Vhmh5V44R01KKO8jedlk-__Kw__IKDLsSJXb2-zB8ORQD4rzuJtLWrra6HRZ4
PlotoManager @ 7/13/2021 8:14:14 AM : WindowStyle: hidden
PlotoManager @ 7/13/2021 8:14:14 AM : Enable AlertWatchdog OnStartUp: true
PlotoManager @ 7/13/2021 8:14:14 AM : Using Plotter: Stotik
PlotoManager @ 7/13/2021 8:14:14 AM : Custom plotter path C:\Users\User\Desktop\madMAx43v3r_chia-plotter_win_v0.1.1\chia_plot.exe
PlotoManager @ 7/13/2021 8:14:14 AM : PlotoMover is enabled: false
PlotoManager @ 7/13/2021 8:14:14 AM : Paths to move final Plots to
--------------------------------------------------------------------------------------------------
PlotoManager @ 7/13/2021 8:14:14 AM : SpawnerConfig
PlotoManager @ 7/13/2021 8:14:14 AM : Total amount of Plots to generate:  18
PlotoManager @ 7/13/2021 8:14:14 AM : Intervall to check between possible Spawns in Minutes:  5
PlotoManager @ 7/13/2021 8:14:14 AM : Max parallel Jobs across all Disks allowed:  15
PlotoManager @ 7/13/2021 8:14:14 AM : Max parallel Jobs across one single Disk allowed:  2
PlotoManager @ 7/13/2021 8:14:14 AM : Max parallel Jobs across all disks in Phase 1 allowed:  9
PlotoManager @ 7/13/2021 8:14:14 AM : Stagger time in minutes to wait between jobs on the same disk:  45
PlotoManager @ 7/13/2021 8:14:14 AM : Stagger time in minutes to wait between jobs on another disk:  15
PlotoManager @ 7/13/2021 8:14:14 AM : Start a new job when another finished starts phase 4:  true
PlotoManager @ 7/13/2021 8:14:14 AM : Replotting is enabled (delete a Plot when on matching drive if a new one enter phase 4):  false
--------------------------------------------------------------------------------------------------
PlotoManager @ 7/13/2021 8:14:14 AM : DiskConfig
PlotoManager @ 7/13/2021 8:14:14 AM : Using temp drives:  I:,E:
PlotoManager @ 7/13/2021 8:14:14 AM : Using -2 drives:  E:
PlotoManager @ 7/13/2021 8:14:14 AM : Using destination drives:  D:
PlotoManager @ 7/13/2021 8:14:14 AM : Will be replotting the following drives:
--------------------------------------------------------------------------------------------------
PlotoManager @ 7/13/2021 8:14:14 AM : JobConfig
PlotoManager @ 7/13/2021 8:14:14 AM : ThreadCount: 4
PlotoManager @ 7/13/2021 8:14:14 AM : BufferSize: 0
PlotoManager @ 7/13/2021 8:14:14 AM : Buckets: 128
PlotoManager @ 7/13/2021 8:14:14 AM : kSize: 32
PlotoManager @ 7/13/2021 8:14:14 AM : EnableBitfield: true
PlotoManager @ 7/13/2021 8:14:14 AM : PoolKey:

**Comment by Yamanipanuchi** [comment]
Found the issue here, in the plotter folder there were some old job files there the script was reading. This is why the script still worked but get this error. I deleted those files have no more error's.
