### ISSUE TITLE
Use CIM instead of WMI

### ISSUE THREAD

**Issue by ninthwalker** [tydeno/Ploto#19]
You've done a lot of work on this I can tell. Thanks for the contribution.
One thing to note, is that depending on the powershel version of users, get-wmiobject has been deprecated and no longer works.
In it's place you can use Get-CimInstance

I swapped it in a couple places in your code and it was a drop-in replacement. You would have to test across all of the places it is used, but just thought I would mention it. Thanks!

**Comment by tydeno** [comment]
@ninthwalker Thats a valid point. I've never thought about, WMI is just common use for me.
You may submit a pull request with your changes for review. I'm happy to test them :)
