### ISSUE TITLE
Aborted Plot Jobs Issues

### ISSUE THREAD

**Issue by aliyucer** [tydeno/Ploto#21]
When I want to create a plot, I get the following error.

PlotoSpawner @ 11.05.2021 6:16:19 PM: No Jobs spawned as either no TempDrives available or max parallel jobs reached. Max Parallel Jobs: 5 Current amount of Jobs: 16

There were tasks I canceled before. I am having problems due to these canceled tasks. When I want to delete, I get the following error.

PlotoRemoveAbortedJobs @ 11.05.2021 6:15:28: Cleaning up ...
Stop-PlotoJob: Cannot bind argument to parameter 'JobId' because it is null.
Horse C: \ Ploto \ Ploto.psm1: 787 char: 34
+ Stop-PlotoJob -JobId $ job.jobid
+ ~~~~~~~~~~
    + CategoryInfo: InvalidData: (:) [Stop-PlotoJob], ParameterBindingValidationException
    + FullyQualifiedErrorId: ParameterArgumentValidationErrorNullNotAllowed, Stop-PlotoJob

Get-PlotoJobs | ft

When I use the command I see 16 tasks aborted and completed ones.

Pc has been restarted many times, so there is no background task either. If it is reading these logs from the logs, how can I clear the logs or solve this problem?

**Comment by Allram** [comment]
If you go to your logs folder and delete the logs, the jobs will start again.

**Comment by tydeno** [comment]
> When I want to create a plot, I get the following error.
> 
> PlotoSpawner @ 11.05.2021 6:16:19 PM: No Jobs spawned as either no TempDrives available or max parallel jobs reached. Max Parallel Jobs: 5 Current amount of Jobs: 16
> 
> There were tasks I canceled before. I am having problems due to these canceled tasks. When I want to delete, I get the following error.
> 
> PlotoRemoveAbortedJobs @ 11.05.2021 6:15:28: Cleaning up ...
> Stop-PlotoJob: Cannot bind argument to parameter 'JobId' because it is null.
> Horse C: \ Ploto \ Ploto.psm1: 787 char: 34
> 
> * Stop-PlotoJob -JobId $ job.jobid
> * ```
>     + CategoryInfo: InvalidData: (:) [Stop-PlotoJob], ParameterBindingValidationException
>     + FullyQualifiedErrorId: ParameterArgumentValidationErrorNullNotAllowed, Stop-PlotoJob
>   ```
> 
> Get-PlotoJobs | ft
> 
> When I use the command I see 16 tasks aborted and completed ones.
> 
> Pc has been restarted many times, so there is no background task either. If it is reading these logs from the logs, how can I clear the logs or solve this problem?

From what I see you're calling Stop-PlotoJob wrong.
It should look like this: 

```powershell
Get-PlotoJobs | ft 
```

```
JobId                                Status    StartTime           TempDrive OutDrive PID   PlotSizeOnTempDisk PlotSizeOnOutDisk ArgumentList                                  PlotId
-----                                ------    ---------           --------- -------- ---   ------------------ ----------------- ------------                                  ------
2d9ca641-f87c-4fba-99f7-e907419fa081 1.5       05/11/2021 17:55:46 I:        K:       6600  34.59 GB           0.00 GB           plots create -k 32 -b 3390 -r 4 -t I:\ -d K:\ c0ff4d09bb47dfaeb6fcb5801b68b61ce7dd8d1856cc36d3944f527ac9ac2d73
3797c10a-6fe9-4f9f-9a36-b981bfb719df 1.6       05/11/2021 17:24:15 J:        K:       14320 55.34 GB           0.00 GB           plots create -k 32 -b 3390 -r 4 -t J:\ -d K:\ 7f52dc698b0770a977bce69be115fb31aceba2d5e68f4537c0cb4409978ad159
5a39b594-cdeb-46aa-bb9f-46fe814b14fc 1.7       05/11/2021 16:59:01 H:        K:       12784 76.09 GB           0.00 GB           plots create -k 32 -b 3390 -r 4 -t H:\ -d K:\ 82659d0729563414e5082e16ecb8c3a15528edcf5cdd607cb986d0842de92ee1
dc80adde-6105-498e-8f1b-e6cc80913bb1 2.2       05/11/2021 16:10:14 E:        K:       12836 157.61 GB          0.00 GB           plots create -k 32 -b 3390 -r 4 -t E:\ -d K:\ 128fcc327c235b0d4b4482aa9f82a332a1c39558675ccee854e614d53f486ea5
95e10ffd-46f2-43e9-b13a-a89444f9912d 2.5       05/11/2021 15:33:11 F:        K:       20220 195.07 GB          0.00 GB           plots create -k 32 -b 3390 -r 4 -t F:\ -d K:\ aba7263e4a88c00048212d0a776ce70037b41e654b0e9b9180a14099cff55ed7
fb43ee0b-7183-4357-bcad-1ef2ddd89401 3.2       05/11/2021 12:22:49 Q:        K:       6736  183.32 GB          0.00 GB           plots create -k 32 -b 3390 -r 4 -t Q:\ -d K:\ 090b3ac6ae7b3a31c933b3401f9d8e96ffd119dc4ddf2f0233be648bab8ca843
bce89504-fa7a-442b-9ea4-10ebf65586f3 3.3       05/11/2021 11:37:35 Q:        K:       13488 153.73 GB          0.00 GB           plots create -k 32 -b 3390 -r 4 -t Q:\ -d K:\ cf08c6de6fd678ee8cea65ddd8a1b18eb495acfa1373d73a893fffbc010300d
```

And now stop the job you want. For me its the first one in the list:
```powershell
Stop-PlotoJob -JobId 2d9ca641-f87c-4fba-99f7-e907419fa081
```
If you run the following function, it deletes all aborted jobs logs and .tmp files:

```powershell
Remove-AbortedPlotoJobs
```
I run this, when I stop a plotjob by closing chia.exe window.

**Comment by aliyucer** [comment]
Thanks @Allram, it works now.

@tydeno, I couldn't do what it said because Job ID and everything else was null. Thanks.
