### ISSUE TITLE
Add ability to define temp 2 drive (-2 param for chia)

### ISSUE THREAD

**Issue by KillaDreams** [tydeno/Ploto#33]
looking through trying to find out if this is able to be done through start-plotospawns and I'm not seeing the ability to do so.

I plot on my NVME then to free up space I have it compress to an SSD then from there I have it move to my HDD farm drive
this allows me to use my fastest drive to do more plots while my mid speed drive does the compressing and transferring to farm drive

-2 [tmp dir 2]: Define a secondary temporary directory for plot creation. This is where Plotting Phase 3 (Compression) and Phase 4 (Checkpoints) occur. Depending on your OS, -2 might default to either -t or -d. Therefore, if either -t or -d are running low on space, it's recommended to set -2 manually. The -2 dir requires an equal amount of working space as the final size of the plot.

**Comment by tydeno** [comment]
Hei there @KillaDreams. You’re right. Currently Ploto has no params for setting -2 dir. However, I‘ll add it to the backlog using this issue.

**Comment by KillaDreams** [comment]
thank you for the quick response looking forward to seeing this implemented

**Comment by tydeno** [comment]
Available for testing as deployed with 558d0f3 on [testing-t2](https://github.com/tydeno/Ploto/tree/testing-t2) (Not pre-tested at all)

**Comment by KillaDreams** [comment]
this is working fine but it stops after a certain amount of plots ran possibly to "no space on T2Drive" but the way the T2 drive works is it acts like a buffer drive to remove some load from TempDrive before moving to OutDrive.

my setup is as follows
Plot - 2TB NVME
T2 - 512 GB RAID 0 SSDs
Farm - HDDs

I am only able to run 5 plots at a time with 120 min delay due to my CPU restrictions. 

The T2Drive should only be checked for "storage size" one time at the beginning of Start-PlotoSpawns since it is only used for compressing from TempDrive to free up space and speed from the main plotting drive.

plot stages 1-2 TempDrive -> Compress files Stage 3 to T2Drive -> move files Stage 4 to OutDrive

JobId           : 91437547-b038-4f2b-92ca-01b934072199
ProcessID       : 3040
OutDrive        : J:
TempDrive       : G:
T2Drive         : H:
ArgumentsList   : plots create -k 32 -b 3390 -r 2 -t G:\ -d J:\ -2 H:\
ChiaVersionUsed : 1.1.5
LogPath         : \.chia\mainnet\plotter\PlotoSpawnerLog_20_5_6_42_91437547-b038-4f2b-92ca-01b934072199_Tmp-G_Out-J.txt
StartTime       : 5/20/2021 6:42:09 AM



--------------------------------------------------------------------
Alerts enabled. In Param and config is there and says send, WhenJobCreated
PlotoManager @ 5/20/2021 6:57:18 AM : Amount of spawned Plots in this iteration: 3
PlotoManager @ 5/20/2021 6:57:18 AM : Overall spawned Plots since start of script: 3
________________________________________________________________________________________
PlotoSpawner @ 5/20/2021 8:49:15 AM : Spawned the following plot Job:


JobId           : 82b0c668-74b6-49c6-9526-4ee387a4e15f
ProcessID       : 17748
OutDrive        : J:
TempDrive       : G:
T2Drive         : None
ArgumentsList   : plots create -k 32 -b 3390 -r 2 -t G:\ -d J:\
ChiaVersionUsed : 1.1.5
LogPath         : .chia\mainnet\plotter\PlotoSpawnerLog_20_5_8_49_82b0c668-74b6-49c6-9526-4ee387a4e15f_Tmp-G_Out-J.txt
StartTime       : 5/20/2021 8:49:07 AM

**Comment by tydeno** [comment]
Thanks for very much for your feedback. So what I understood: For the t2drive, its irrelevant how many plots it can hold and we dont need to check upon that. It will be used to offload compression for a job that uses that param.

So we don't need to calculate and check the following properties to define in which many jobs a t2drive can be used:
* T2Drive.AmountOfPlotsInProgress
* T2Drive.AmountOfPlotsToTempMax
* T2Drive.AvailableAmountToPlot


## I need some more understanding
- We rather focus on the overall, initial free space of the disk, but from my understanding right now, is also neglibile?
- At which point would we define not to use that disk, ie when completely full (Because we maybe do 16x jobs in parallel, all pointing to 1-2x t2drives)?
- And for the fact that one would want to use more than 1x t2 drive, we'd need a way to determine the most suitable, available t2drive.


This brings a few questions to my mind: Do we need to check free space at all? Or does that chia.exe itself and determines what/when it can offload? And if we check free space initially, what for?

**Comment by KillaDreams** [comment]
Ok so I hope I can answer these questions properly also forgive me I'm on my phone with the github app and it's very hard to understand the layout if this 

> ## Some questions for my understanding
> - We rather focus on the overall, initial free space of the disk, but from my understanding right now, is also neglibile?

The max overall space in your example is 4 at a time but that would be at the same exact time as the compressing build new files on the T2Drives it doesn't use the full 107 GB size instantly.

> - At which point would we define not to use that disk, ie when completely full (Because we maybe do 16x jobs in parallel, all pointing to 1-2x t2drives)?

Would these 16 jobs be delayed or all at same time? Then as you calculated you would need 4 512GB size T2Drives to be able to do this

I don't think we would ever tell it not to use T2 unless we disable it in config file.

>    - Check Jobs upon phase of job that uses this disk? 

Possibly have it check jobs in stage 3 and stage 4 then calculate 

MAX minus stage 3 plus stage 4 is greater than 0 then allow new plot to spawn 



> - And for the fact that one would want to use more than 1x t2 drive, we'd need a way to determine the most suitable, available t2drive.


Using the 16 parallel example as above it could
Rotate through the multiple T2Drives with each new starting plot  so it may look as follows with Drive - Plots

T2D 1 - 1,5,9,13
T2D 2 - 2,6,10,14
T2D 3 - 3,7,11,15
T2D 4 - 4,8,12,16

>    - Again, maybe upon amount of jobs on this disk in given phase?



> - Do we need to check free space at all? Or does that chia.exe itself and determines what/when it can offload? And if we check free space initially, what for?

Yes. If chia runs out of temp space it will wait 5 mins and try again and as long as a plot is in stage 4 drive space will free up so back to max 4 example if the 5th plot is trying to compress to same T2D then as long another plot is already in stage 4 the space will free up for the 5th to compress once the stage 4 completes the move and deletes the compressed file

>

**Comment by tydeno** [comment]
Based on that, I adjusted Get-PlotoT2Drives with the following:
- To get active Jobs, added a filter that only gets jobs on that drive in p3 and p4. (Jobs not in P3/4 will not be added to calculation)
- Rotation trough t2 drives is already there.

Availabele in latest commit 2eb07ab on branch https://github.com/tydeno/Ploto/tree/t2-enhancement. Not pre-tested may break. Will test tonigt along with branch dynamic-stagger

**Comment by PiSCaRGoT** [comment]
If I may add, having an option to "sync" t2 and outdrives may also be desirable to some setups (like mine).

If t2 and outdrive is the same, chia.exe skips the Phase 5 (or the Copy phase) all together. This can potentially save up 4-7minutes of job time (depending on your outdrive) so that a new job can be (considered to be) started immediately.

I leave the copying from t2 to actual destination to be done by PlotoMover instead.

**Comment by KillaDreams** [comment]
@PiSCaRGoT I just set t2drive and outdrive the same and then have plotomoves loop from outdrive to final location

**Comment by realdevnullius** [comment]
Small side-question... Would it be weird to have my smaller 1TB NVMe bootdisk act as temp-2 drive, while my 1.7 TB SSDs do the regular temp-stuff? I see everyone here does it the other way around :)

**Comment by KillaDreams** [comment]
> Small side-question... Would it be weird to have my smaller 1TB NVMe bootdisk act as temp-2 drive, while my 1.7 TB SSDs do the regular temp-stuff? I see everyone here does it the other way around :)

You want your fastest drive to be your tempdrives then to offload space to T2drives to free up space and transfer speed from main drive so you can continue to plot more faster while the T2Drive does the transfer to the outdrive
