### ISSUE TITLE
Ungültiger JSON-Primitiv ?

### ISSUE THREAD

**Issue by manowar40** [tydeno/Ploto#38]
Ich habe nur die Webhook Adresse eingetragen.  Bekomme aber dann diese Meldung. Das JSON File ist auch im ordner C:\Users\me\\.chia\mainnet\config
![image](https://user-images.githubusercontent.com/12272240/118379228-0e74d300-b5d9-11eb-93ea-32df3346cac9.png)

**Comment by chefsas** [comment]
I'm getting the same thing. I have the JSON file with my webhook URLs in the config folder.
![Screenshot 2021-05-15 234135](https://user-images.githubusercontent.com/74569709/118385731-38c59100-b5d7-11eb-8cf4-8d663c1abf0e.png)
![2021-05-15_23-43-24](https://user-images.githubusercontent.com/74569709/118385765-91952980-b5d7-11eb-85b0-dbbc72093aea.jpg)

**Comment by chefsas** [comment]
Nevermind -- I figured out the problem. Line 14 should have the comma removed at the end. It should read:

"PeriodOfReportInHours": "1"

instead of:

"PeriodOfReportInHours": "1",

**Comment by aliyucer** [comment]
Thanks @chefsas it's work.

> Nevermind -- I figured out the problem. Line 14 should have the comma removed at the end. It should read:
> 
> "PeriodOfReportInHours": "1"
> 
> instead of:
> 
> "PeriodOfReportInHours": "1",

Thanks @chefsas it's work.

**Comment by tydeno** [comment]
Sorry for comitting it wrong. Glad you guys fixed it.

**Comment by tydeno** [comment]
The SummaryReport may also be broken. I remember hardcoding a path to the module. I‘ll fix it when I‘m home. In the meantime, if you want to get periodical StatusReports, change the path to the module in the function „Start-PlotoFy“ to match your system.

**Comment by tydeno** [comment]
Fixed. Adjusted Configfile.

**Comment by KillaDreams** [comment]
Yeah I didn't want to create another issue, so I commented on the file on the line where it was messed up? I figured this out around 2pm EST, were you unable to see that?
