### ISSUE TITLE
Add SSD and CPU Temperature in SummaryReport for Drives

### ISSUE THREAD

**Issue by aliyucer** [tydeno/Ploto#39]
Hello,

Is it possible to send notifications (discord) to SSD and CPU temperature at specified intervals? or can only be set for high temperature.

https://howtoitforge.com/how-to-show-disk-temperature-in-powershell/

**Comment by tydeno** [comment]
We can send it at given intervalls. For example the one defined in the config, is meant to get atatus reports from time to tile about finished jobs, jobs in progress, outdrive/temprive overview. So we can include the temp.

**Comment by tydeno** [comment]
Findings so far:
* To get Storage relibaility counters, we need to run PlotoFy as Admin.
* Interesting properties of Get-PhysicalDisk are:
   *  BusType
   *  MediaType
   *  FriendlyName  
* We need a way to map PhysicalDisk to LogicalDisk; -> Rewrite Get-PlotoOut and TempDrives to use Get-Disk
