### ISSUE TITLE
Allow Staggering upon PlotJobPhase on Drive

### ISSUE THREAD

**Issue by tydeno** [tydeno/Ploto#4]
Add a more dynamic way of staggering. Currently staggering is done by simply specifying an amount of Minutes to be waited before a plot is spawned on a separate or the same disk. 

By continously monitoring PlotJob phase and its effects on ressource usage, a more dynamic way of staggering would be possible.

**Comment by PiSCaRGoT** [comment]
Hi Tydeno, love your work so far. Thank you.

Just wondering, are you still working on this feature? Actually setting a max jobs in Phase 1 would be perfect, and would compliment your other feature well - Max Jobs on Same Disk

**Comment by tydeno** [comment]
hei @PiSCaRGoT; Thanks for your kind words :)

Yes, I am. Not actively right now, but I will get back to it.

**Comment by tydeno** [comment]
I just commited a few changes to the branch [dynamic-stagger](https://github.com/tydeno/Ploto/tree/dynamic-stagger) that added the following:
* Ability to define max parallel jobs in phase 1 per each disk
* Ability to define max parallel jobs in phase 1 on all disks
* Ability to launch a new plot when a given phase is completed (EarlyStart, set to 3 advised. So when a job completed phase 3, the next can be started) 

The whole changed code is untested for now (no chia.exe here to test). @PiSCaRGoT If you'd like to try it out, yu may get the source from the dynamic-stagger branch :)

**Comment by PiSCaRGoT** [comment]
Perfect! Thanks for turning it around so quickly, let me give it a shot and let you know how it works.

**Comment by tydeno** [comment]
@PiSCaRGoT I just tested it, has some flaws. Not advised to test for you rn. I need to dig deeper, but I'm pretty occupied this Weekend. Might take a bit longer than expected.
