### ISSUE TITLE
Get-PlotoJobs indexes to null array ($status[($status.count-1)])

### ISSUE THREAD

**Issue by OhNOherewegoagain** [tydeno/Ploto#40]
PS C:\Windows\system32> Import-Module "C:\Users\Mupuk\Downloads\Ploto-main\Ploto.psm1"
PS C:\Windows\system32> Start-PlotoSpawns -BufferSize 3400 -Thread 6 -InputAmountToSpawn 15 -OutDriveDenom "out" -TempDriveDenom "plot" -WaitTimeBetweenPlotOnSeparateDisks 15 -WaitTimeBetweenPlotOnSameDisk 60 -MaxParallelJobsOnAllDisks 15 -MaxParallelJobsOnSameDisk 3 -EnableBitfield $true
>>
Loaded Alarmcoinfig successfully
Cannot index into a null array.
At C:\Users\Mupuk\Downloads\Ploto-main\Ploto.psm1:908 char:9
+         $CurrentStatus = $status[($status.count-1)]
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray

Cannot index into a null array.
At C:\Users\Mupuk\Downloads\Ploto-main\Ploto.psm1:908 char:9
+         $CurrentStatus = $status[($status.count-1)]
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray

Cannot index into a null array.
At C:\Users\Mupuk\Downloads\Ploto-main\Ploto.psm1:908 char:9
+         $CurrentStatus = $status[($status.count-1)]
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray

Cannot index into a null array.
At C:\Users\Mupuk\Downloads\Ploto-main\Ploto.psm1:908 char:9
+         $CurrentStatus = $status[($status.count-1)]
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray

Cannot index into a null array.
At C:\Users\Mupuk\Downloads\Ploto-main\Ploto.psm1:908 char:9
+         $CurrentStatus = $status[($status.count-1)]
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray

Cannot index into a null array.
At C:\Users\Mupuk\Downloads\Ploto-main\Ploto.psm1:908 char:9
+         $CurrentStatus = $status[($status.count-1)]
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray

Current JobCountAll0: 4
Cannot index into a null array.
At C:\Users\Mupuk\Downloads\Ploto-main\Ploto.psm1:908 char:9
+         $CurrentStatus = $status[($status.count-1)]
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray

Cannot index into a null array.
At C:\Users\Mupuk\Downloads\Ploto-main\Ploto.psm1:908 char:9
+         $CurrentStatus = $status[($status.count-1)]
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray

**Comment by tydeno** [comment]
Can you run the exact same command with -verbose param and post the output?

**Comment by tydeno** [comment]
@OhNOherewegoagain Can you run the exact same command with -verbose param and post the output?

**Comment by tydeno** [comment]
Anyway I'll rewrite it with Measure-Object in a sec. That should help as it will return 0 instead of $null

**Comment by tydeno** [comment]
Do you have logs from preivously used chia GUI plot jobs in your C:\Users\me\.chia\mainnet\plotter folder?
If so, delete those. 

So all logs that dont look like this:
* PlotoSpawnerLog_9_5_20_26_b5f050c1-70d3-42ee-ac37-b47240c0e164_Tmp-I_Out-K.txt
* PlotoSpawnerLog_9_5_20_26_b5f050c1-70d3-42ee-ac37-b47240c0e164_Tmp-I_Out-K@Stat.txt

**Comment by tydeno** [comment]
I assume its fixed (testing shows no isntance of this error anymore). If you still encounter this issue, feel free to reopen.
