### ISSUE TITLE
InputAmountToSpawn Param is ignored

### ISSUE THREAD

**Issue by KillaDreams** [tydeno/Ploto#48]
I currently have -InputAmountToSpawn 17 

it has spawned 22 jobs and is not stopping my Farm storage is full and I haven't added another drive yet so now it has "wasted" power, cpu usage, disk TDW, and time.

this has done such a great job of keeping the plotting going smoothly I wasn't aware it was so close to being done my original guess was ~72 hours from now

-----------------------------------------------------------------
PlotoSpawner @ + 5/17/2021 10:15:17 AM +: Count of Jobs on this disk: 12
PlotoSpawner @ 5/17/2021 10:15:17 AM : Spawned the following plot Job:

JobId           : 0f9a5d8a-dbf1-4ff5-8b2a-be0270b33da6
ProcessID       : 3584
OutDrive        : I:
TempDrive       : G:
ArgumentsList   : plots create -k 32 -b 3390 -r 2 -t G:\ -d I:\
ChiaVersionUsed : 1.1.5
LogPath         : .chia\mainnet\plotter\PlotoSpawnerLog_17_5_10_15_0f9a5d8a-dbf1-4ff5-8b2a-be0270b33da6_Tmp-G_Out-I.tx
                  t
StartTime       : 5/17/2021 10:15:13 AM

-----------------------------------------------------------------
PlotoManager @ 5/17/2021 12:30:36 PM : Amount of spawned Plots in this iteration: 39 /3
PlotoManager @ 5/17/2021 12:30:36 PM : Overall spawned Plots since start of script: 13
________________________________________________________________________________________
Loaded Alarmcoinfig successfully
Current JobCountAll0: 5
PlotoSpawner @ 5/17/2021 12:36:03 PM : Spawned the following plot Job:

JobId           : 62c1f7db-32ac-4ec3-9c7b-b3998188bfc4
ProcessID       : 11616
OutDrive        : I:
TempDrive       : G:
ArgumentsList   : plots create -k 32 -b 3390 -r 2 -t G:\ -d I:\
ChiaVersionUsed : 1.1.5
LogPath         : .chia\mainnet\plotter\PlotoSpawnerLog_17_5_12_36_62c1f7db-32ac-4ec3-9c7b-b3998188bfc4_Tmp-G_Out-I.tx
                  t
StartTime       : 5/17/2021 12:36:03 PM

--------------------------------------------------------------------
Alerts enabled. In Param and config is there and says send, WhenJobCreated
PlotoManager @ 5/17/2021 12:51:04 PM : Amount of spawned Plots in this iteration: 3 /3
PlotoManager @ 5/17/2021 12:51:04 PM : Overall spawned Plots since start of script: 5.33333333333333
________________________________________________________________________________________
Loaded Alarmcoinfig successfully
Current JobCountAll0: 5
PlotoSpawner @ 5/17/2021 3:03:19 PM : Spawned the following plot Job:

JobId           : 48113c24-aa3b-49a8-8306-b97fc20b2483
ProcessID       : 17168
OutDrive        : I:
TempDrive       : G:
ArgumentsList   : plots create -k 32 -b 3390 -r 2 -t G:\ -d I:\
ChiaVersionUsed : 1.1.5
LogPath         : .chia\mainnet\plotter\PlotoSpawnerLog_17_5_15_3_48113c24-aa3b-49a8-8306-b97fc20b2483_Tmp-G_Out-I.txt
StartTime       : 5/17/2021 3:03:19 PM

--------------------------------------------------------------------
Alerts enabled. In Param and config is there and says send, WhenJobCreated
PlotoManager @ 5/17/2021 3:18:19 PM : Amount of spawned Plots in this iteration: 3 /3
PlotoManager @ 5/17/2021 3:18:20 PM : Overall spawned Plots since start of script: 2.77777777777778
________________________________________________________________________________________
Loaded Alarmcoinfig successfully
Current JobCountAll0: 5
PlotoSpawner @ 5/17/2021 5:31:09 PM : Spawned the following plot Job:

JobId           : 45f79fc2-677a-4a8f-961a-b214f02162fc
ProcessID       : 18268
OutDrive        : I:
TempDrive       : G:
ArgumentsList   : plots create -k 32 -b 3390 -r 2 -t G:\ -d I:\
ChiaVersionUsed : 1.1.5
LogPath         : .chia\mainnet\plotter\PlotoSpawnerLog_17_5_17_31_45f79fc2-677a-4a8f-961a-b214f02162fc_Tmp-G_Out-I.tx
                  t
StartTime       : 5/17/2021 5:31:09 PM

--------------------------------------------------------------------
Alerts enabled. In Param and config is there and says send, WhenJobCreated
PlotoManager @ 5/17/2021 5:46:11 PM : Amount of spawned Plots in this iteration: 3 /3
PlotoManager @ 5/17/2021 5:46:11 PM : Overall spawned Plots since start of script: 1.92592592592593
________________________________________________________________________________________
Loaded Alarmcoinfig successfully
Current JobCountAll0: 5
PlotoSpawner @ 5/17/2021 7:48:11 PM : Spawned the following plot Job:

JobId           : 5a6be07b-dfd7-433b-ab96-0b0cd22e8eb9
ProcessID       : 17592
OutDrive        : I:
TempDrive       : G:
ArgumentsList   : plots create -k 32 -b 3390 -r 2 -t G:\ -d I:\
ChiaVersionUsed : 1.1.5
LogPath         : .chia\mainnet\plotter\PlotoSpawnerLog_17_5_19_48_5a6be07b-dfd7-433b-ab96-0b0cd22e8eb9_Tmp-G_Out-I.tx
                  t
StartTime       : 5/17/2021 7:48:11 PM

--------------------------------------------------------------------
Alerts enabled. In Param and config is there and says send, WhenJobCreated
PlotoManager @ 5/17/2021 8:03:11 PM : Amount of spawned Plots in this iteration: 3 /3
PlotoManager @ 5/17/2021 8:03:12 PM : Overall spawned Plots since start of script: 1.64197530864198
________________________________________________________________________________________
Loaded Alarmcoinfig successfully
Current JobCountAll0: 5
PlotoSpawner @ 5/17/2021 9:55:06 PM : Spawned the following plot Job:

JobId           : bae59121-6670-4689-a9f9-801e120e0177
ProcessID       : 15392
OutDrive        : I:
TempDrive       : G:
ArgumentsList   : plots create -k 32 -b 3390 -r 2 -t G:\ -d I:\
ChiaVersionUsed : 1.1.5
LogPath         : .chia\mainnet\plotter\PlotoSpawnerLog_17_5_21_55_bae59121-6670-4689-a9f9-801e120e0177_Tmp-G_Out-I.tx
                  t
StartTime       : 5/17/2021 9:55:06 PM

--------------------------------------------------------------------
Alerts enabled. In Param and config is there and says send, WhenJobCreated
PlotoManager @ 5/17/2021 10:10:06 PM : Amount of spawned Plots in this iteration: 3 /3
PlotoManager @ 5/17/2021 10:10:06 PM : Overall spawned Plots since start of script: 1.54732510288066
________________________________________________________________________________________
Loaded Alarmcoinfig successfully
Current JobCountAll0: 5
PlotoSpawner @ 5/18/2021 12:02:04 AM : Spawned the following plot Job:

JobId           : 106ad07f-b20d-4b97-bcbc-d6b3c24fa800
ProcessID       : 9056
OutDrive        : I:
TempDrive       : G:
ArgumentsList   : plots create -k 32 -b 3390 -r 2 -t G:\ -d I:\
ChiaVersionUsed : 1.1.5
LogPath         : .chia\mainnet\plotter\PlotoSpawnerLog_18_5_0_2_106ad07f-b20d-4b97-bcbc-d6b3c24fa800_Tmp-G_Out-I.txt
StartTime       : 5/18/2021 12:02:04 AM

--------------------------------------------------------------------
Alerts enabled. In Param and config is there and says send, WhenJobCreated
PlotoManager @ 5/18/2021 12:17:05 AM : Amount of spawned Plots in this iteration: 3 /3
PlotoManager @ 5/18/2021 12:17:05 AM : Overall spawned Plots since start of script: 1.51577503429355
________________________________________________________________________________________
Loaded Alarmcoinfig successfully
Current JobCountAll0: 5
PlotoSpawner @ 5/18/2021 2:19:51 AM : Spawned the following plot Job:

JobId           : aecb2660-5d41-46fd-ae33-3020aac7021f
ProcessID       : 16388
OutDrive        : I:
TempDrive       : G:
ArgumentsList   : plots create -k 32 -b 3390 -r 2 -t G:\ -d I:\
ChiaVersionUsed : 1.1.5
LogPath         : .chia\mainnet\plotter\PlotoSpawnerLog_18_5_2_19_aecb2660-5d41-46fd-ae33-3020aac7021f_Tmp-G_Out-I.txt
StartTime       : 5/18/2021 2:19:51 AM

--------------------------------------------------------------------
Alerts enabled. In Param and config is there and says send, WhenJobCreated
PlotoManager @ 5/18/2021 2:34:51 AM : Amount of spawned Plots in this iteration: 3 /3
PlotoManager @ 5/18/2021 2:34:52 AM : Overall spawned Plots since start of script: 1.50525834476452
________________________________________________________________________________________
Loaded Alarmcoinfig successfully
Current JobCountAll0: 5
PlotoSpawner @ 5/18/2021 4:43:12 AM : Spawned the following plot Job:

JobId           : 87d40611-e764-4514-9138-046bbc8a4992
ProcessID       : 5436
OutDrive        : I:
TempDrive       : G:
ArgumentsList   : plots create -k 32 -b 3390 -r 2 -t G:\ -d I:\
ChiaVersionUsed : 1.1.5
LogPath         : .chia\mainnet\plotter\PlotoSpawnerLog_18_5_4_43_87d40611-e764-4514-9138-046bbc8a4992_Tmp-G_Out-I.txt
StartTime       : 5/18/2021 4:43:12 AM

--------------------------------------------------------------------
Alerts enabled. In Param and config is there and says send, WhenJobCreated
PlotoManager @ 5/18/2021 4:58:12 AM : Amount of spawned Plots in this iteration: 3 /3
PlotoManager @ 5/18/2021 4:58:13 AM : Overall spawned Plots since start of script: 1.50175278158817
________________________________________________________________________________________
Loaded Alarmcoinfig successfully
Current JobCountAll0: 5
PlotoSpawner @ 5/18/2021 7:12:14 AM : Spawned the following plot Job:

JobId           : 1ac5a50e-717a-4b77-8805-3b42818d0591
ProcessID       : 4712
OutDrive        : I:
TempDrive       : G:
ArgumentsList   : plots create -k 32 -b 3390 -r 2 -t G:\ -d I:\
ChiaVersionUsed : 1.1.5
LogPath         : .chia\mainnet\plotter\PlotoSpawnerLog_18_5_7_12_1ac5a50e-717a-4b77-8805-3b42818d0591_Tmp-G_Out-I.txt
StartTime       : 5/18/2021 7:12:13 AM

--------------------------------------------------------------------
Alerts enabled. In Param and config is there and says send, WhenJobCreated
PlotoManager @ 5/18/2021 7:27:14 AM : Amount of spawned Plots in this iteration: 3 /3
PlotoManager @ 5/18/2021 7:27:14 AM : Overall spawned Plots since start of script: 1.50058426052939
________________________________________________________________________________________
Loaded Alarmcoinfig successfully
Current JobCountAll0: 6
PlotoSpawner @ 5/18/2021 7:32:42 AM : No Jobs spawned as either no TempDrives available or max parallel jobs reached. Max Parallel Jobs:  6 Current amount of Jobs: 6

**Comment by tydeno** [comment]
@KillaDreams Thats not good if it overcommits. Sorry for that. What version of Ploto are you using? See from the .psm1 itself at the very beginning. I remember adding a check for -InputAmountToSpawn in the nested functions. But that might not be enough yet.

**Comment by KillaDreams** [comment]
current version 1.0.8.2.4.3

**Comment by tydeno** [comment]
@KillaDreams Assuming your farm storage is filled now; What happens when you run:
 Get-PlotoOutDrives -OutDriveDenom $YourDenom

Do you get any object returned?

**Comment by KillaDreams** [comment]
The drive isn't full yet it will be I stopped the last 2 that started and
also stopped ploto from spawning new jobs.  I have room for the last 2 that
are plotting right now they are almost done with stage 3 I'll run that
command and let you know once they are done

**Comment by KillaDreams** [comment]
i just added the second drive but it pulls fine looks like the config git reset reloaded upon max jobs and it lost track

Get-PlotoOutDrives -OutDriveDenom farm


DriveLetter         : I:
ChiaDriveType       : Out
VolumeName          : Farm 1
FreeSpace           : 95.69
TotalSpace          : 0
IsPlottable         : False
AmountOfPlotsToHold : 0

DriveLetter         : J:
ChiaDriveType       : Out
VolumeName          : Farm2
FreeSpace           : 4657.25
TotalSpace          : 0
IsPlottable         : True
AmountOfPlotsToHold : 46

**Comment by tydeno** [comment]
I just realized I completely messed this up with the latest commit to the testbranch. I fixed something else but completely broke the ability of Ploto to keep track of how many jobs it spawned. Need to rework. And finally fix the amount of spawned jobs display message.

**Comment by KillaDreams** [comment]
Alright well thanks again I'm running jobs 10 at a time instead of the max
HD can hold still also trying to tweak my max numbers

**Comment by tydeno** [comment]
InputAmountToSpawn Param is blatantly ignored for now with latest pull request #51 . 
Why? I focus on successfully spawning jobs as fast as possible rather than complying with that param. Overcommit should not be possible anyway due to checking OutDrives. And also If a jobs fills a drive, you may copy/move stuff from on that drive and te job can continue. Will be fixed though!

**Comment by KillaDreams** [comment]
yes but the current space of the temp drive is available before the moving of a previous plot, when it checks the OutDrives the prior plot hasn't been moved yet and therefore it spawns another plot... but that plot will never be able to finish and be moved due to outdrive having no space remaining

**Comment by tydeno** [comment]
> yes but the current space of the temp drive is available before the moving of a previous plot, when it checks the OutDrives the prior plot hasn't been moved yet and therefore it spawns another plot... but that plot will never be able to finish and be moved due to outdrive having no space remaining once previous job has moved

Gotcha. I will invest some more time today after and let you know what turns out.
