### ISSUE TITLE
Improper job count

### ISSUE THREAD

**Issue by KillaDreams** [tydeno/Ploto#55]
Everytime the the alerts enabled comes up and it runs the checks it adds the iteration number to the total since start of script and I believe this then causes it to think it has reached the max? Plots to plot

![Screenshot_20210521-183659_Remote Desktop.jpg](https://user-images.githubusercontent.com/53876155/119207445-dd2a5600-ba63-11eb-84ac-bc845c3769ca.jpg)

![Screenshot_20210521-210815_Remote Desktop.jpg](https://user-images.githubusercontent.com/53876155/119211597-b9bdd600-ba78-11eb-8731-d9b115df9e3d.jpg)

**Comment by tydeno** [comment]
Interesting, thanks for reporting. I will take a look. I think this is due to that the notification gets addedd to the output upon which "Start-PlotJobs" counts.

**Comment by KillaDreams** [comment]
would a "jobs remaining" be better instead of the "overall spawned plots since start" 

I changed the code around I'm trying to see if this works so far so good it

```
        if ($SpawnedPlots)
            {
                $SpawnedCountThisIteration = ($SpawnedPlots | Measure-Object).Count
                $SpawnedCountOverall = $InputAmountToSpawn - $SpawnedCountThisIteration

                Write-Host "PlotoManager @"(Get-Date)": Amount of spawned Plots so far:" $SpawnedCountThisIteration
                Write-Host "PlotoManager @"(Get-Date)": remaining Plots to spawn:" $SpawnedCountOverall
                Write-Host "________________________________________________________________________________________"
            }

        Start-Sleep ($IntervallToWait*60)
    }
    
    Until ($SpawnedCountOverall = 0)
    Write-Host "We are done!" -ForegroundColor Green

    $VerbosePreference = $oldverbose

}
```

![image](https://user-images.githubusercontent.com/53876155/119232339-87e55780-baea-11eb-8a90-661a75d43f78.png)

**Comment by tydeno** [comment]
Glad you got it going! I fixed with piping the Output of the Discord notification functions to Out-Null. I‘m currently testing and will probably push it later.
