### ISSUE TITLE
Rotate outdrives selected by new plot job.

### ISSUE THREAD

**Issue by Sp4rkR4t** [tydeno/Ploto#56]
At the minute setting off ploto with multiple temp and multiple out drives seems to generate a lot of plots to go on the out drive with the most free space which is leading to extreme slowdown in phase 4, it would be better if there was a way to instruct it to pick a out drive that currently doesn't have a job planned for it.

**Comment by tydeno** [comment]
You are right, it currently always selects the drive with most free outspace. Got to change that to OutDrive that has the least jobs in progress. Thanks for the feedback!

**Comment by tydeno** [comment]
Testing shows its works as expected. Pulling changes to main.
