### ISSUE TITLE
[bug report] - Updated chia to 1.1.6 now ploto doesn't spawn jobs

### ISSUE THREAD

**Issue by Sp4rkR4t** [tydeno/Ploto#61]
I updated both chia and ploto this morning to their latest versions and ploto was refusing to spawn jobs the terminal was just sitting on the interval to wait line with no errors, after a lot of re-installing and renaming of things I found that it was the old ploto logs that were making it hang up, once I moved them out of the plotter folder and restarted ploto it all worked flawlessly.

**Comment by tydeno** [comment]
Thx for your report. Yea I need to handle logs differently. Its rather picky right now. Log flushing helps always. I do not delete but move them to another folder for further reference.
