### ISSUE TITLE
Question about Config

### ISSUE THREAD

**Issue by Yamanipanuchi** [tydeno/Ploto#69]
Running script, Love it. But its been going for about 2 hours now and has only spawned two plotters. I have 4 plot disks and 1 out disk. all 500g or more. Am I missing something in the config?

`  "JobConfig": [
      {
        "IntervallToCheckInMinutes": "5",
        "InputAmountToSpawn": "100", 
        "WaitTimeBetweenPlotOnSeparateDisks": "15",
        "WaitTimeBetweenPlotOnSameDisk": "30",
        "MaxParallelJobsOnAllDisks": "6",
        "MaxParallelJobsOnSameDisk": "2",
        "MaxParallelJobsInPhase1OnAllDisks" : "10",
        "StartEarly": "true",
        "StartEarlyPhase": "4",
        "BufferSize": "5000",
        "Thread": "4",
        "Bitfield": "true",
        "FarmerKey": "",
        "PoolKey": ""
      }
    ],`

![image](https://user-images.githubusercontent.com/4724631/119551741-d3983b00-bd4e-11eb-9697-b3487c87f940.png)

**Comment by Yamanipanuchi** [comment]
I think I see the issue.. Two of my disks are 300gb. There large enough to plot on but the script isn't allowing it.

**Comment by Yamanipanuchi** [comment]
Yes, That was it. I changed the size from 290 to 250 and it worked. Been plotting on these driver for a while now so I'm sure there big enough. They happen to be REALLY fast drives so..

**Comment by tydeno** [comment]
Glad you got it resolved by changing the script! :) 290 is a simple generalization I do. And I also prefer some overhead.
