### ISSUE TITLE
Chia 1.1.6 fresh Windows installation: Plotter folder does not exist?

### ISSUE THREAD

**Issue by realdevnullius** [tydeno/Ploto#76]
`PS C:\Windows\system32> Start-PlotoSpawns
PlotoManager @ 2-6-2021 19:04:09 : Ploto Manager started.
PlotoManager @ 2-6-2021 19:04:09 : Loading config from  C:\Users\Gebruiker\.chia\mainnet\config\PlotoSpawnerConfig.json...
PlotoManager @ 2-6-2021 19:04:09 : InputAmountToSpawn: 100
PlotoManager @ 2-6-2021 19:04:09 : Intervall to wait: 5
PlotoManager @ 2-6-2021 19:04:09 : PlotoFy is set to startup. Checking for active PlotoFy jobs...
PlotoManager @ 2-6-2021 19:04:09 : We have found active PlotoFy jobs. Stopping it and starting fresh...

Id     Name            PSJobTypeName   State         HasMoreData     Location             Command
--     ----            -------------   -----         -----------     --------             -------
3      PlotoFy         BackgroundJob   Running       True            localhost            ...
PlotoManager @ 2-6-2021 19:04:09 : Started PlotoFy successfully. Check your Discord
---------------------------------------------------------------------------------
Get-ChildItem : Cannot find path '`C:\Users\Gebruiker\.chia\mainnet\plotter\`' because it does not exist.
At `C:\Users\Gebruiker\Downloads\Ploto\Ploto.psm1`:1145 char:9
+ $logs = Get-ChildItem $PlotterBaseLogPath | Where-Object {$_.Name -no ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Gebrui...ainnet\plotter\:String) [Get-ChildItem], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand

Invoke-PlotoJob : Cannot bind argument to parameter 'OutDriveDenom' because it is null.
At `C:\Users\Gebruiker\Downloads\Ploto\Ploto.psm1`:1106 char:104
+ ... ize $BufferSize -Thread $Thread -OutDriveDenom $OutDriveDenom -TempDr ...
+                                                    ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-PlotoJob], ParameterBindingValidationExcept
   ion
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Invoke-PlotoJob`

I installed chia 1.1.6 today on a fresh desktop. There indeed is no folder "plotter" on my machine. The official wallet is started and syncing. User error? Or bug? :)

**Comment by realdevnullius** [comment]
there's also a "\" missing in the first path statement:
C:\Users\Gebruiker.chia\mainnet instead of C:\Users\Gebruiker\.chia\mainnet

That looks like a user error? :) BUT... C:\Users\Gebruiker\.chia\mainnet\plotter isn't a directory either. I did an explorer search on "plotter" and it found 0 results.

**Comment by KillaDreams** [comment]
Missing the \ after gebruiker and before .chia ??

> C:\Users\Gebruiker.chia\mainnet instead of C:\Users\Gebruiker.chia\mainnet
>
> That looks like a user error? :) BUT...
> C:\Users\Gebruiker.chia\mainnet\plotter isn't a directory either. I did an
> explorer search on "plotter"
>

**Comment by realdevnullius** [comment]
yeah that was github - should be corrected now: it removed the `\` in view. But good catch :)

I really don't have the plotter folder on my fresh PC with fresh 1.1.6 (Windows). Where is it? :(

:)

**Comment by KillaDreams** [comment]
I believe it is generated by Chia.exe (GUI) or chia.exe (CLI) upon plotting
for first time but it should be exactly where it's pointed at so just
create the folder manually and you should be good to go

**Comment by realdevnullius** [comment]
I was just testing a plot with the GUI :) And if that doesn't work I'll create a plotter folder. Thank you! I'll update & close once confirmed.

Appreciated

**Comment by KillaDreams** [comment]
Did you setup the config file and drop it in .chia\mainnet\config

**Comment by realdevnullius** [comment]
Confirmed: after starting a plot with the GUI a plotter folder was created and it contains a log file, no software. All good! My bad apparently :)

**Comment by realdevnullius** [comment]
> Did you setup the config file and drop it in .chia\mainnet\config

Yep did that too. I think it's solved and I'll close it for now. If I learn differently, I'll start bugging ya'all again ;-)
