### ISSUE TITLE
Null array when initializing the jobs

### ISSUE THREAD

**Issue by Daniel-Fan** [tydeno/Ploto#8]
Number of plot drive: 1
Number of out drive: 2

Get null array for `status`
```
PS C:\Users\fanyu> Start-PlotoSpawns -InputAmountToSpawn 12 -OutDriveDenom "out" -TempDriveDenom "plot" -WaitTimeBetweenPlotOnSeparateDisks 15 -WaitTimeBetweenPlotOnSameDisk 20 -MaxParallelJobsOnAllDisks 3 -MaxParallelJobsOnSameDisk 3 -EnableBitfield $false

Cannot index into a null array.
At C:\Users\fanyu\Downloads\Ploto-main\Ploto-main\Ploto.psm1:472 char:9
+         $CurrentStatus = $status[($status.count-1)]
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray

Cannot index into a null array.
At C:\Users\fanyu\Downloads\Ploto-main\Ploto-main\Ploto.psm1:472 char:9
+         $CurrentStatus = $status[($status.count-1)]
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray

PlotoSpawner @ 2021-05-07 7:07:39 PM : Spawned the following plot Job:


JobId           : dddf12ef-39d2-449a-b1d3-2201d9547a79
ProcessID       : 2236
OutDrive        : E:
```

Observe instantly starting for two plot jobs, one job for each out drive, both of them are on the same plot drive.

Usually would expect that the job could be delayed to start on the same plot drive.

**Comment by wuzhefang** [comment]
yes, how to fix it?

**Comment by wuzhefang** [comment]
@tydeno maybe it's need a sleep before the log file ready.

**Comment by wuzhefang** [comment]
@tydeno by the way. The two jobs will started when it comes to a new temp drive. Hope to fix it.

**Comment by tydeno** [comment]
Thats weird. What version are you running? You can get it from the module. Because there is a param that allows to sleep before spawning a job on the same drive. Anyway, I‘ll look into it later today.

**Comment by Daniel-Fan** [comment]
the same issue happened in both `1.1.3` and `1.1.4`

**Comment by tydeno** [comment]
Found the culprit. When iterating trough the drives, the script did not sleep between spawning jobs on the same drive for the first time. Added a lil sleep after we launch a job on a disk and it has space for another and param allows it.
