### ISSUE TITLE
StartEarly and StartEarlyPhase examples?

### ISSUE THREAD

**Issue by realdevnullius** [tydeno/Ploto#80]
`         "StartEarly": "true",	| Enable EarlyStart (when jobs completed StatusEarlyPhase)
          "StartEarlyPhase": "3",   | Defines when a job should be early started. If a job completes phase 3 in this example, it is not considered an active job anymore and makes room for another to spawn early.`

I must admit... I'm unsure as of what to do with these 2 options? And how do they relate to `WaitTimeBetweenPlotOnSameDisk`. As far as I know I set it to wait 150 minutes but I had a new plot spawned after about 50 minutes or so. Which surprised me :)

I've set StartEarlyPhase to 4, will that mess things up? :) If so, what? 

Appreciated!

**Comment by KillaDreams** [comment]
Once a plot reaches the phase you set for startearly and new plot will spawn as long as you have not met your max plots, and maxplotsphase1
