### ISSUE TITLE
Is Ploto just a Chia scheduler or does it do waaaay more? Like finding the correct timings and such?

### ISSUE THREAD

**Issue by realdevnullius** [tydeno/Ploto#81]
See subject: I'm anything but a code reader but I noticed you for sure had a lot of code! So, I'm left wondering... What kind of magic things does Ploto do? Feel free to brag USA-style ;-)

**Comment by tydeno** [comment]
As of right now, Ploto is basically „just“ a chia.exe scheduler that spawns jobs based on your configuration. But yes, it does more.
Mainly on the convenience side of things. 

It protects your drives from overcomits by file size, as its aware of jobs on each and every drive used for plotting.

It always looks for the fastest available drive with the least amount of jobs in progress.

It also leverages Discord Webhooks to keep you in the loop about whats going on with your plot jobs.

On every cycle, it checks for aborted plot jobs (where chia.exe instance died) and deletes all associated logs and temp files to free up space.

It allows you to automatically move final plots around your drives and your network (UNC paths).

So I think these are pretty much all features to brag about :)
