### ISSUE TITLE
Request: use a seperate log folder for Ploto?

### ISSUE THREAD

**Issue by realdevnullius** [tydeno/Ploto#82]
```
PlotoSpawner redirects the output of chia.exe to to the following path:

C:\Users\Tydeno\.chia\mainnet\plotter\
```

Can we change that to:
`C:\Users\Tydeno\.chia\mainnet\ploto_logs`?

**Comment by KillaDreams** [comment]
Don't know why you would want another folder for the logs? I'm sure it's possible but I doubt @tydeno would do it for you, you'd have to go in and change all of the code everywhere to the new location

**Comment by tydeno** [comment]
> ```
> PlotoSpawner redirects the output of chia.exe to to the following path:
> 
> C:\Users\Tydeno\.chia\mainnet\plotter\
> ```
> 
> 
>      
>   
> 
> Can we change that to:
> 
> `C:\Users\Tydeno\.chia\mainnet\ploto_logs`?

As @KillaDreams stated, it would be surely possible. I think a definable logpath in config would be handy here. 

To help me understand the request, could you elaborate as to why you would like to move the log destination?
