### ISSUE TITLE
Suggestion for cooperation)

### ISSUE THREAD

**Issue by OhNOherewegoagain** [tydeno/Ploto#84]
Hello tydeno, i was just woundering if the two masterminds would work together you can create a masterpiece in chia plotting!
There is a youtuber MrPig91 that works on PSChiaPlotter https://github.com/MrPig91/PSChiaPlotter, he has created a GUI in powershell, i am not sure how it would work out, but you can think of combining your both ideas and create a new, full of features chiaplotter) 
just a suggestion, everything is up to you!

**Comment by tydeno** [comment]
The idea is great, but to be honest there is so much logic in Ploto and PSChiaPlottr now, that I think merging these two projects would be a very rough task. There a different underlying concepts being used.
