### ISSUE TITLE
[CHANGE REQUEST] change to use drive letters instead of drive names

### ISSUE THREAD

**Issue by lanceosaurus** [tydeno/Ploto#94]
During setup, it's unclear as to what is required for the drive 'denom'.  Most users understand drive letters.  Most users don't know the names of their drives.

And additional wrinkle is what happens if you have drives with the same name?

And for additional points, allow use of drive letter and folder paths rather than forcing the use of the entire drive.

**Comment by tydeno** [comment]
There are so many valid points in this. I will ultimately change from denoms to driveletters/foldernames.
